
#ifndef L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_
#define L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_

#include "uart3.hpp"



void sendtoapp(char *data,Uart3 &u3);




#endif /* L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_ */
