/*
 * bluetoothtransmission.h
 *
 *  Created on: 27-Nov-2017
 *      Author: pratap
 */

#ifndef L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_
#define L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_





#endif /* L5_APPLICATION_PERIODIC_SCHEDULER_BLUETOOTHTRANSMISSION_H_ */
