
#ifndef L5_APPLICATION_PERIODIC_SCHEDULER_RECEIVE_HEARTBEATS_H_
#define L5_APPLICATION_PERIODIC_SCHEDULER_RECEIVE_HEARTBEATS_H_



void receive_heartbeats(void);

#endif /* L5_APPLICATION_PERIODIC_SCHEDULER_RECEIVE_HEARTBEATS_H_ */
