
#ifndef L5_APPLICATION_PERIODIC_SCHEDULER_SEND_BLUETOOTH_HEARTBEAT_H_
#define L5_APPLICATION_PERIODIC_SCHEDULER_SEND_BLUETOOTH_HEARTBEAT_H_


void send_bluetooth_hertbeat(void);




#endif /* L5_APPLICATION_PERIODIC_SCHEDULER_SEND_BLUETOOTH_HEARTBEAT_H_ */
